exclude: ^(blib2to3/|profiling/|tests/data/)
repos:
  - repo: git://github.com/doublify/pre-commit-isort
    rev: v4.3.0
    hooks:
      - id: isort
        name: Check by isort
        exclude: ^lib_formatter_logger/config.py
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      name: Check by black
      language_version: python3.7
      exclude: ^lib_formatter_logger/config.py
      exclude: ^setup.py
      args: [--line-length=120, --safe, --check]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    - id: flake8
      name: Check by flake8
      exclude: ^lib_formatter_logger/config.py
      args: [--max-line-length=120, --ignore=F401, --ignore=W503]